RM-6903: arm: imxrt1170: Reserve clock IDs and DTS nodes to support ADC for i.MXRT1170 SoC.
EmcraftSystems/linux-imx pull request #32
Opened 2023-11-08 09:34 UTC by asanochkin-emcraft

Build  the rootfs project with these changes applied and run it on the rt1170 board.
Check that the project is booted on the board.

2023-11-08 10:05 UTC, vdskvortsov requested changes

2023-11-08 10:05 UTC, vdskvortsov commented on include/dt-bindings/clock/imxrt1170-clock.h
> +#define IMXRT1170_CLK_ROOT_ADC1 		36
Please keep the sorting order for the root clocks as per the reference manual. ADC1 and ADC2 registers are between SEMC and GPT1, so let's assign IDs 29 and 30 to the IMXRT1170_CLK_ROOT_ADC1 and ADC2

2023-11-08 10:05 UTC, vdskvortsov commented on include/dt-bindings/clock/imxrt1170-clock.h
> +#define IMXRT1170_CLK_USB			48
Shouldn't we add IDs for the ADC gates (LPCG55 and LPCG56 as per the processor reference manual) ?

2023-11-08 12:22 UTC, vdskvortsov approved these changes

2023-11-09 04:45 UTC, vladimirkhusainov-emcraft commented on arch/arm/boot/dts/imxrt1170.dtsi
> +			/* TBD */
Why TBD's in those two sections? Shouldn't we add a more meaningful comment instead?

2023-11-09 13:48 UTC, vladimirkhusainov-emcraft approved these changes

2023-11-09 13:48 UTC, merged