RM6923 support i2c in linux on imxrt1170
EmcraftSystems/linux-imx pull request #39
Opened 2023-12-01 09:42 UTC by asanochkin-emcraft

**Unit test**
Build the rootfs project with these changes applied.

Unit test performed and is a success.

2023-12-01 10:14 UTC, vdskvortsov requested changes

2023-12-01 10:14 UTC, vdskvortsov commented on arch/arm/boot/dts/imxrt1170.dtsi
> +			/*clocks = <&clks IMXRT1170_CLK_LPI2C1>, <&clks IMXRT1170_CLK_IPG_PODF>;
Please remove the unused code.

2023-12-01 10:14 UTC, vdskvortsov commented on arch/arm/boot/dts/imxrt1170.dtsi
> +			compatible = "fsl,imx7ulp-lpi2c";
Shouldn't we also add `address-cells` and `size-cells` here? Please extend unit test to make sure there are not warnings when build DTB.

2023-12-01 10:14 UTC, vdskvortsov commented on arch/arm/boot/dts/imxrt1170.dtsi
> +			clocks = <&clks IMXRT1170_CLK_LPI2C2>;
Missed `clocks-names` property for the lpi2c[2..6] nodes. If it is not needed, please remove corresponding property in `lpi2c1`.

2023-12-01 10:14 UTC, vdskvortsov commented on drivers/clk/imx/clk-imxrt1170.c
> +"pll3_div2", "pll1_div5", "pll2_pfd3"};
Must be  `"pll3_div2", "pll1_div5", "pll2_sys", "pll2_pfd3"` Refer to IMXRT1170 RM.

2023-12-01 10:14 UTC, vdskvortsov commented on drivers/clk/imx/clk-imxrt1170.c
> +	{ IMXRT1170_CLK_ROOT_LPI2C5, "lpi2c5_root", lpi2c1_6_sels, (41 * 0x80), },
`lpi2c5` and `lpi2c6` root clocks use different mux. Refer to IMXRT1170 RM.

2023-12-01 13:38 UTC, vdskvortsov requested changes

2023-12-01 13:38 UTC, vdskvortsov commented on drivers/clk/imx/clk-imxrt1170.c
> +"pll3_pfd3", "pll3_clk", "pll2_pfd3", "pll1_div5"};
There is no `pll3_clk` clock defined in this driver. Did you mean `pll3_sys`?

2023-12-01 14:05 UTC, asanochkin-emcraft commented on drivers/clk/imx/clk-imxrt1170.c
> +"pll3_pfd3", "pll3_clk", "pll2_pfd3", "pll1_div5"};
Corrected.

2023-12-04 16:29 UTC, asanochkin-emcraft commented on arch/arm/boot/dts/imxrt1170.dtsi
> +			/*clocks = <&clks IMXRT1170_CLK_LPI2C1>, <&clks IMXRT1170_CLK_IPG_PODF>;
Done

2023-12-04 16:31 UTC, asanochkin-emcraft commented on arch/arm/boot/dts/imxrt1170.dtsi
> +			compatible = "fsl,imx7ulp-lpi2c";
Moved these nodes from rootfs.dts.IMXRT117X_NXPEVK. Done.

2023-12-05 07:15 UTC, vdskvortsov approved these changes

2023-12-05 08:23 UTC, vdskvortsov requested changes
Please made the slave mode in the LPI2C driver configurable. Currently the CONFIG_I2C_SLAVE option is mandatory to build the LPI2C driver, should made it optional.

2023-12-05 09:10 UTC, vdskvortsov approved these changes

2023-12-05 14:35 UTC, merged