RM-6933: arm: imxrt: Add invocation of traps_v7m_init()
EmcraftSystems/linux-imx pull request #40
Opened 2023-12-26 10:10 UTC by asanochkin-emcraft

**Unit test**
1. Boot the imxrt1170 board by the roots project with these changes applied
2. Check that the system is booted successfully and operates as expected
3. Run the following test program and check the result:
#include <stdio.h>
void main(void)
{
        int a = 1000;
        int b = 0;

        printf("Result = %d\n", a / b);
}
- On imxrt1170 release 3.0.4:
/ # /tmp/t
Result = 0
/ #
- On imxrt1170 with these changes applied:
/ # /tmp/t

t: fault at 0x8212173e [pc=0x8212173e, sp=0x81a3fd30]
Divide By 0

Segmentation fault

2023-12-26 13:21 UTC, vdskvortsov approved these changes

2023-12-26 18:15 UTC, vladimirkhusainov-emcraft requested changes

2023-12-26 18:15 UTC, vladimirkhusainov-emcraft commented on arch/arm/kernel/traps-v7m.c
> +#if 0 /* commented out until unaligned access in uclibc is fixed */
Let's do this as follows (not sure about the exact grammar, please check): 

if !defined(CONFIG_ARM_V7M_NO_UNALIGN_TRP) & 0

We want to preserve a reference to CONFIG_ARM_V7M_NO_UNALIGN_TRP in this code.

2024-01-07 06:45 UTC, vladimirkhusainov-emcraft approved these changes

2024-01-07 06:46 UTC, merged